import { portalHTML } from './portal-private.js';
const shell="<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><meta name=\"robots\" content=\"noindex,nofollow\"><title>Client Portal | Detcord Digital</title><link rel=\"icon\" href=\"/favicon.png\"><link rel=\"stylesheet\" href=\"/portal.css?v=20261004-mobile\"></head><body><header><a href=\"/\" aria-label=\"Detcord Digital home\"><img src=\"/detcord-logo-transparent.png\" alt=\"Detcord Digital\"></a><a href=\"/\">Back to website</a></header><main><section id=\"setup-password\" class=\"login\" hidden><span class=\"eyebrow\">DETCORD / ACCOUNT SETUP</span><h1>Create your password.</h1><p>Choose a secure password to activate your portal account.</p><form id=\"activate-account\"><label>New password<input name=\"password\" type=\"password\" minlength=\"12\" maxlength=\"256\" autocomplete=\"new-password\" required></label><label>Confirm password<input name=\"confirm\" type=\"password\" minlength=\"12\" maxlength=\"256\" autocomplete=\"new-password\" required></label><button>Activate account</button></form></section><section id=\"signin\" class=\"login\"><span class=\"eyebrow\">DETCORD / CLIENT ACCESS</span><h1>Your work.<br>Your portal.</h1><p>Reports, shared photos, and invoices in one place.</p><form id=\"login\"><label>Email<input name=\"email\" type=\"text\" autocomplete=\"username\" required placeholder=\"you@company.com\"></label><label>Password<input name=\"password\" type=\"password\" autocomplete=\"current-password\" required></label><button>Sign in</button></form><p class=\"muted\">Need access or a password reset? <a href=\"mailto:info@detcorddigital.com\">Contact Detcord</a>.</p></section><p id=\"notice\" role=\"status\" aria-live=\"polite\"></p></main><script src=\"/portal-login.js?v=gate-20261004\" defer></script></body></html>";
export async function portalPage(request,env,checkSession){
 const url=new URL(request.url);
 if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});
 const session=await checkSession(new Request(url.origin+'/api/portal/me',{headers:request.headers}),env);
 const headers=new Headers({'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex, nofollow','Vary':'Cookie'});
 if(session.status===200){return new Response(request.method==='HEAD'?null:portalHTML,{headers});}
 return new Response(request.method==='HEAD'?null:shell,{headers});
}
