const $=s=>document.querySelector(s);let me,selected='';const notice=t=>$('#notice').textContent=t;
async function api(path,options={}){const r=await fetch('/api/portal'+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options.headers}});const d=await r.json();if(!r.ok){if(r.status===401&&path!='/login'){signedOut();}throw Error(d.error||'Request failed');}return d;}
function path(p){return p+(me?.admin?'?client='+encodeURIComponent(selected):'');}
function signedOut(){window.dispatchEvent(new Event('portal-clear'));me=null;$('#signin').hidden=false;$('#dashboard').hidden=true;$('#login').reset();}
async function start(){me=await api('/me');$('#signin').hidden=true;$('#dashboard').hidden=false;$('#welcome').textContent=me.admin?'Client workspace':me.client.name;$('#admin').hidden=!me.admin;$('#report-upload').hidden=!me.admin;$('#invoice-create').hidden=!me.admin;$('#change-password').hidden=me.role==='admin';$('#new-client-section').hidden=me.role!=='admin';$('#reset-client-section').hidden=me.role!=='admin';$('#staff-management').hidden=me.role!=='admin';if(me.role==='admin')await loadStaff();notice('');if(me.admin){const d=await api('/clients');const selector=$('#client');selector.replaceChildren(new Option('Select a client',''));d.clients.forEach(c=>selector.add(new Option(c.name+' · '+c.email,c.id)));selector.value=selected;$('#workspace').hidden=!selected;if(selected)await refresh();}else{$('#workspace').hidden=false;await refresh();}}
function node(tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;}
async function refresh(){const {items}=await api(path('/items'));window.dispatchEvent(new CustomEvent('portal-items',{detail:{items,admin:me.admin,selected,client:me.client}}));for(const [kind,id] of [['report','report-list'],['photo','photo-list'],['invoice','invoice-list']]){const list=$('#'+id);list.replaceChildren();const rows=items.filter(i=>i.kind===kind);if(!rows.length){list.append(node('p',kind==='report'?'Your reports will appear here once published.':kind==='photo'?'No shared photos yet.':'No invoices yet.','muted'));continue;}rows.forEach(item=>{const card=node('article','','card');card.append(node('h3',item.title),node('p',new Date(item.created).toLocaleDateString(),'meta'));const actions=node('div','','actions');if(kind==='invoice'){card.append(node('p',new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(item.data.amount/100),'amount'),node('p',(item.data.status==='paid'?'Paid':'Unpaid')+' · Due '+item.data.due,'status'));if(item.data.status!=='paid'){if(item.data.payment){const a=node('a','Pay invoice','pay');a.href=item.data.payment;a.target='_blank';a.rel='noopener noreferrer';actions.append(a);}else card.append(node('p','Contact Detcord for payment instructions.','muted'));}if(me.admin&&item.data.status!=='paid'){const b=node('button','Mark paid','secondary');b.onclick=()=>markPaid(item);actions.append(b);}}else{card.append(node('p',(item.data.size/1000000).toFixed(2)+' MB','meta'));const a=node('a',kind==='report'?'Download report':'Download photo');a.href='/api/portal'+path('/file/'+item.id);actions.append(a);}if(me.admin||kind==='photo'){const b=node('button','Delete','secondary');b.onclick=async()=>{if(!confirm('Delete “'+item.title+'”?'))return;try{await api(path('/items/'+item.id),{method:'DELETE'});await refresh();notice('Deleted.');}catch(e){notice(e.message);}};actions.append(b);}card.append(actions);list.append(card);});}}
async function markPaid(item){if(!confirm('Confirm payment has been received for '+item.title+'?'))return;try{await api(path('/invoice/'+item.id),{method:'PATCH',body:JSON.stringify({status:'paid'})});await refresh();notice('Invoice marked paid.');}catch(e){notice(e.message);}}
function form(id,handler){$('#'+id).onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;notice('');try{await handler(new FormData(e.target),e.target);}catch(err){notice(err.message);}finally{button.disabled=false;}};}
form('login',async d=>{await api('/login',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});await start();});
$('#logout').onclick=async()=>{try{await api('/logout',{method:'POST',body:'{}'});signedOut();selected='';notice('Signed out.');}catch(e){notice(e.message);}};
$('#client').onchange=async e=>{window.dispatchEvent(new Event('portal-clear'));selected=e.target.value;$('#workspace').hidden=!selected;try{if(selected)await refresh();if(me.role==='admin')await loadStaff();notice('');}catch(e){notice(e.message);}};
form('new-client',async(d,f)=>{const result=await api('/clients',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});selected=result.id;f.reset();await start();notice('Client created. Share their login details privately.');});
for(const [id,kind] of [['report-upload','report'],['photo-upload','photo']])form(id,async(d,f)=>{d.set('kind',kind);await api(path('/upload'),{method:'POST',body:d});f.reset();await refresh();notice(kind==='report'?'Report published.':'Photo uploaded.');});
form('invoice-create',async(d,f)=>{const data=Object.fromEntries(d);data.amount=Math.round(Number(data.amount)*100);await api(path('/invoice'),{method:'POST',body:JSON.stringify(data)});f.reset();await refresh();notice('Invoice created.');});
form('reset-password',async(d,f)=>{if(!selected)throw Error('Select a client first.');await api('/password',{method:'POST',body:JSON.stringify({client:selected,password:d.get('password')})});f.reset();notice('Password reset. Existing client sessions have been signed out.');});
form('change-password',async d=>{await api('/password',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});signedOut();notice('Password changed. Sign in with your new password.');});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!==b.dataset.tab);});
start().catch(e=>{signedOut();if(e.message!=='Please sign in.')notice(e.message);});

async function loadStaff(){const {staff}=await api('/staff');const list=$('#staff-assignments');list.replaceChildren();if(!staff.length){list.append(node('p','No sales rep accounts yet.','muted'));return;}staff.forEach(rep=>{const label=node('label','','check');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=rep.clients.includes(selected);checkbox.disabled=!selected;checkbox.onchange=async()=>{checkbox.disabled=true;try{await api('/assignment',{method:'POST',body:JSON.stringify({staff:rep.id,client:selected,assigned:checkbox.checked})});notice(checkbox.checked?'Rep assigned to this client.':'Rep access removed.');}catch(e){checkbox.checked=!checkbox.checked;notice(e.message);}finally{checkbox.disabled=false;}};label.append(checkbox,document.createTextNode(rep.name+' · '+rep.email));list.append(label);});}
form('new-staff',async(d,f)=>{await api('/staff',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});f.reset();await loadStaff();notice('Rep account created. Assign their clients and share login details privately.');});
