const $=s=>document.querySelector(s);let me,selected='',currentReportId='';const notice=t=>$('#notice').textContent=t;
async function api(path,options={}){const r=await fetch('/api/portal'+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options.headers}});const d=await r.json();if(!r.ok){if(r.status===401&&path!='/login'){signedOut();}throw Error(d.error||'Request failed');}return d;}
function path(p){return p+(me?.admin?'?client='+encodeURIComponent(selected):'');}
function signedOut(){window.dispatchEvent(new Event('portal-clear'));me=null;$('#signin').hidden=false;$('#setup-password').hidden=true;$('#dashboard').hidden=true;$('#login').reset();}
async function start(){me=await api('/me');$('#signin').hidden=true;$('#dashboard').hidden=false;$('#welcome').textContent=me.admin?'Client workspace':me.client.name;$('#admin').hidden=me.role!=='admin';const sh=$('#sales-home');if(sh)sh.hidden=me.role!=='sales';$('#report-upload').hidden=!me.admin;$('#invoice-create').hidden=!me.admin;$('#change-password').hidden=me.role==='admin';setClientMode(selected?'existing':null);$('#reset-client-section').hidden=me.role!=='admin';$('#staff-management').hidden=me.role!=='admin';$('#delete-client').hidden=me.role!=='admin';$('#delete-client').disabled=!selected;if(me.role==='admin'){await loadStaff();await loadAdminAssignments();}notice('');if(me.admin){const d=await api('/clients');const selector=$('#client');selector.replaceChildren(new Option('Select a client',''));d.clients.forEach(c=>selector.add(new Option(c.name+' · '+c.email,c.id)));selector.value=selected;if(me.role==='sales')setupSalesHome(d.clients);const mc=$('#metric-clients');if(mc)mc.textContent=d.clients.length;const ma=$('#metric-attention');if(ma)ma.textContent=d.clients.length?Math.min(d.clients.length,5):0;renderAdminActions(d.clients);$('#workspace').hidden=!selected;if(selected)await refresh();}else{$('#workspace').hidden=false;await refresh();}}
function node(tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;}
async function refresh(){const {items}=await api(path('/items'));window.__portalItems=items;if(me?.role==='sales'){const m=$('#sales-metric-contracts');if(m)m.textContent=items.filter(i=>i.kind==='contract').length;}window.dispatchEvent(new CustomEvent('portal-items',{detail:{items,admin:me.admin,selected,client:me.client}}));renderReports(items);for(const [kind,id] of [['photo','photo-list'],['invoice','invoice-list']]){const list=$('#'+id);list.replaceChildren();const rows=items.filter(i=>i.kind===kind);if(!rows.length){list.append(node('p',kind==='photo'?'No shared photos yet.':'No invoices yet.','muted'));continue;}rows.forEach(item=>{const card=node('article','','card');card.append(node('h3',item.title),node('p',new Date(item.created).toLocaleDateString(),'meta'));const actions=node('div','','actions');if(kind==='invoice'){card.append(node('p',new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(item.data.amount/100),'amount'),node('p',(item.data.status==='paid'?'Paid':'Unpaid')+' · Due '+item.data.due,'status'));if(item.data.status!=='paid'){if(item.data.payment){const a=node('a','Pay invoice','pay');a.href=item.data.payment;a.target='_blank';a.rel='noopener noreferrer';actions.append(a);}else card.append(node('p','Contact Detcord for payment instructions.','muted'));}if(me.admin&&item.data.status!=='paid'){const b=node('button','Mark paid','secondary');b.onclick=()=>markPaid(item);actions.append(b);}}else{card.append(node('p',(item.data.size/1000000).toFixed(2)+' MB','meta'));const a=node('a','Download photo');a.href='/api/portal'+path('/file/'+item.id);actions.append(a);}if(me.admin||kind==='photo'){const b=node('button','Delete','secondary');b.onclick=async()=>{if(!confirm('Delete “'+item.title+'”?'))return;try{await api(path('/items/'+item.id),{method:'DELETE'});await refresh();notice('Deleted.');}catch(e){notice(e.message);}};actions.append(b);}card.append(actions);list.append(card);});}}
function renderReports(items){const list=$('#report-list');if(!list)return;list.replaceChildren();const rows=items.filter(i=>i.kind==='report'||i.kind==='report-draft'&&i.data?.report);if(!rows.length){list.append(node('p',me.admin?'No saved reports yet. Generated reports will appear here automatically.':'No reports have been published to your portal yet.','muted'));return;}rows.forEach(item=>{const card=node('article','','card saved-report-card');card.append(node('h3',item.title),node('p',new Date(item.created).toLocaleDateString()+(item.kind==='report-draft'?(item.data.published?' · Published to customer':' · Private'):' · Published'),'meta'));const actions=node('div','','actions');if(item.kind==='report'){const a=node('a','Download report');a.href='/api/portal'+path('/file/'+item.id);actions.append(a);}else{const open=node('button','Open','secondary');open.type='button';open.onclick=()=>openSavedReport(item,false);const present=node('button','Present','secondary');present.type='button';present.onclick=()=>openSavedReport(item,true);actions.append(open,present);if(me.admin){const pub=node('button',item.data.published?'Remove from Customer Portal':'Load to Customer Portal','secondary');pub.type='button';pub.onclick=()=>toggleReportPublish(item);actions.append(pub);}}if(me.admin){const del=node('button','Delete','secondary');del.type='button';del.onclick=async()=>{if(!confirm('Delete “'+item.title+'”?'))return;try{await api(path('/items/'+item.id),{method:'DELETE'});await refresh();notice('Deleted.');}catch(e){notice(e.message);}};actions.append(del);}card.append(actions);list.append(card);});}
function openSavedReport(item,present=false){const report=item.data?.report||{};currentReportId=item.id;$('#report-preview-title').textContent=item.title;$('#goat-win').textContent=report.biggestWin||'No supported win identified.';$('#goat-opportunity').textContent=report.biggestOpportunity||'No supported opportunity identified.';$('#goat-change').textContent=report.whatChanged||'No supported change identified.';$('#goat-attention').textContent=report.needsAttention||'No supported issue identified.';const body=$('#report-preview-body');body.replaceChildren();if(report.executiveSummary)body.append(node('p',report.executiveSummary));(report.gamePlan||[]).forEach((x,i)=>body.append(node('p',(i+1)+'. '+x)));const deck=$('#report-preview');deck.querySelectorAll('.generated-report-slide').forEach(x=>x.remove());(report.slides||[]).forEach(s=>{const slide=node('article','','report-slide generated-report-slide');slide.append(node('span','DETCORD / REPORT','eyebrow'),node('h2',s.title||'Report'));if(s.subtitle)slide.append(node('p',s.subtitle,'muted'));const ul=node('ul');(s.bullets||[]).forEach(b=>ul.append(node('li',b)));slide.append(ul);const brand=document.createElement('img');brand.className='report-slide-brand';brand.src='/detcord-logo-transparent.png';brand.alt='Detcord Digital';slide.append(brand);deck.insertBefore(slide,deck.querySelector('.report-slide-brand')||deck.querySelector('.report-export-bar'));});document.querySelector('[data-tab="report-builder"]')?.click();$('#report-draft-form').closest('.report-studio').hidden=true;deck.hidden=false;if(present)startReportPresentation();}
async function toggleReportPublish(item){const publishing=!item.data.published;if(publishing&&!confirm('Are you sure you want to load this report to the customer portal? The customer will be able to see it.'))return;if(!publishing&&!confirm('Remove this report from the customer portal? The saved Detcord copy will remain.'))return;try{await api(path(publishing?'/report-publish':'/report-unpublish'),{method:'POST',body:JSON.stringify({id:item.id})});notice(publishing?'Report loaded to the customer portal.':'Report removed from the customer portal.');await refresh();}catch(e){notice(e.message);}}
async function markPaid(item){if(!confirm('Confirm payment has been received for '+item.title+'?'))return;try{await api(path('/invoice/'+item.id),{method:'PATCH',body:JSON.stringify({status:'paid'})});await refresh();notice('Invoice marked paid.');}catch(e){notice(e.message);}}
function form(id,handler){$('#'+id).onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;notice('');try{await handler(new FormData(e.target),e.target);}catch(err){notice(err.message);}finally{button.disabled=false;}};}
const setupParams=new URLSearchParams(location.search),setupId=setupParams.get('setup'),rawHash=location.hash.slice(1),setupToken=new URLSearchParams(rawHash).get('token')||rawHash;if(setupId&&setupToken){$('#signin').hidden=true;$('#setup-password').hidden=false;form('activate-account',async(d)=>{if(d.get('password')!==d.get('confirm'))throw Error('Passwords do not match.');await api('/activate',{method:'POST',body:JSON.stringify({id:setupId,token:setupToken,password:d.get('password')})});history.replaceState({},'',location.pathname);$('#setup-password').hidden=true;$('#signin').hidden=false;notice('Password created. Sign in with your email and new password.');});}
form('login',async d=>{await api('/login',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});await start();});
$('#logout').onclick=async()=>{try{await api('/logout',{method:'POST',body:'{}'});signedOut();selected='';notice('Signed out.');}catch(e){notice(e.message);}};
$('#client').onchange=async e=>{window.dispatchEvent(new Event('portal-clear'));selected=e.target.value;setClientMode('existing');$('#delete-client').disabled=!selected;$('#workspace').hidden=!selected;try{if(selected)await refresh();if(me.role==='admin')await loadStaff();notice('');}catch(e){notice(e.message);}};
form('new-client',async(d,f)=>{const result=await api('/clients',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});selected=result.id;const requestAccess=d.get('requestAccess')==='on',accessEmail=d.get('accessEmail')||d.get('email');f.reset();await start();if(requestAccess){document.querySelector('#access-email').value=accessEmail;await prepareGoogleAccess(accessEmail);}else notice(result.invitation?.accepted?'Client created. Password setup invitation sent.':'Client created, but the invitation was not sent: '+(result.invitation?.error||'Check email configuration.'));});
for(const [id,kind] of [['report-upload','report'],['photo-upload','photo']])form(id,async(d,f)=>{d.set('kind',kind);await api(path('/upload'),{method:'POST',body:d});f.reset();await refresh();notice(kind==='report'?'Report published.':'Photo uploaded.');});
form('invoice-create',async(d,f)=>{const data=Object.fromEntries(d);data.amount=Math.round(Number(data.amount)*100);await api(path('/invoice'),{method:'POST',body:JSON.stringify(data)});f.reset();await refresh();notice('Invoice created.');});
form('reset-password',async(d,f)=>{if(!selected)throw Error('Select a client first.');await api('/password',{method:'POST',body:JSON.stringify({client:selected,password:d.get('password')})});f.reset();notice('Password reset. Existing client sessions have been signed out.');});
form('change-password',async d=>{await api('/password',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});signedOut();notice('Password changed. Sign in with your new password.');});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!==b.dataset.tab);});
// Invitation setup must finish before the normal session/login check.
if(!setupId&&!setupToken)start().catch(e=>{signedOut();if(e.message!=='Please sign in.')notice(e.message);});
else if(!setupId||!setupToken){$('#signin').hidden=true;$('#setup-password').hidden=true;notice('This setup link is incomplete. Ask Detcord for a new invitation.');}

async function loadStaff(){const {staff}=await api('/staff');const mr=$('#metric-reps');if(mr)mr.textContent=staff.length;const list=$('#staff-assignments');list.replaceChildren();if(!staff.length){list.append(node('p','No sales rep accounts yet.','muted'));return;}staff.forEach(rep=>{const label=node('label','','check');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=rep.clients.includes(selected);checkbox.disabled=!selected;checkbox.onchange=async()=>{checkbox.disabled=true;try{await api('/assignment',{method:'POST',body:JSON.stringify({staff:rep.id,client:selected,assigned:checkbox.checked})});notice(checkbox.checked?'Rep assigned to this client.':'Rep access removed.');}catch(e){checkbox.checked=!checkbox.checked;notice(e.message);}finally{checkbox.disabled=false;}};label.append(checkbox,document.createTextNode(rep.name+' · '+rep.email));const remove=node('button','Delete rep account','secondary');remove.type='button';remove.onclick=async()=>{if(!confirm('Delete '+rep.name+'’s account? Login access will be revoked.'))return;try{await api('/staff/'+rep.id,{method:'DELETE'});await loadStaff();notice('Rep account deleted and its email removed from the portal.');}catch(e){notice(e.message);}};const invite=node('button','Send / resend invitation','secondary');invite.type='button';invite.onclick=async()=>{invite.disabled=true;try{const result=await api('/staff/'+rep.id+'/invite',{method:'POST',body:'{}'});notice('Invitation accepted for delivery to '+rep.email+'.');await loadStaff();}catch(e){notice(e.message);}finally{invite.disabled=false;}};const row=node('div');row.append(label,invite,remove);if(rep.invitation)row.append(node('p',rep.invitation.status==='accepted'?'Invitation accepted for delivery · '+new Date(rep.invitation.at).toLocaleString():rep.invitation.error||'Invitation sending…','muted'));list.append(row);});}
form('new-staff',async(d,f)=>{const result=await api('/staff',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});f.reset();await loadStaff();notice('Rep account created. '+(result.invitation.accepted?'Password setup invitation accepted for delivery.':'Invitation was not sent: '+result.invitation.error)+' Assign their clients when ready.');});

$('#delete-client').onclick=async()=>{if(!selected||!confirm('Delete this client account? Login access will be revoked; signed agreements and records are retained.'))return;try{await api('/clients/'+selected,{method:'DELETE'});selected='';window.dispatchEvent(new Event('portal-clear'));await start();notice('Client account deleted and its email removed from the portal.');}catch(e){notice(e.message);}};

function setClientMode(mode){
$('#new-client-section').hidden=mode!=='new';
$('#new-client-section').open=mode==='new';
$('#existing-client-section').hidden=mode!=='existing';
$('#choose-new-client').setAttribute('aria-pressed',String(mode==='new'));
$('#choose-existing-client').setAttribute('aria-pressed',String(mode==='existing'));
$('#workspace').hidden=mode!=='existing'||!selected;
$('#reset-client-section').hidden=me?.role!=='admin'||mode!=='existing'||!selected;
$('#delete-client').hidden=me?.role!=='admin'||mode!=='existing'||!selected;
}
$('#choose-new-client').onclick=()=>{window.dispatchEvent(new Event('portal-clear'));selected='';$('#client').value='';setClientMode('new');$('#new-client input[name="name"]').focus();};
$('#choose-existing-client').onclick=()=>{setClientMode('existing');$('#client').focus();};

function renderAdminActions(clients){
 const box=$('#admin-next-actions');if(!box)return;box.replaceChildren();
 const actions=[];
 if(!clients.length)actions.push(['Create your first client','Add a client and send their secure setup invitation.','new']);
 else {
   clients.slice(0,3).forEach(c=>actions.push([c.name,'Open workspace, review activity, contracts and files.','open',c.id]));
 }
 actions.forEach(([title,desc,type,id])=>{const row=node('div','','next-action');const copy=node('div');copy.append(node('strong',title),node('p',desc,'muted'));const b=node('button',type==='new'?'New Client':'Open','secondary');b.type='button';b.onclick=()=>{if(type==='new'){$('#choose-new-client').click();document.querySelector('.admin-console')?.scrollIntoView({behavior:'smooth'});}else{selected=id;$('#client').value=id;setClientMode('existing');$('#workspace').hidden=false;refresh().catch(e=>notice(e.message));document.querySelector('.tabs')?.scrollIntoView({behavior:'smooth'});}};row.append(copy,b);box.append(row);});
}
function goatAdminReply(q){
 const s=q.toLowerCase();
 if(/new|add|create/.test(s)&&/client|customer|lead/.test(s)){ $('#choose-new-client').click();document.querySelector('.admin-console')?.scrollIntoView({behavior:'smooth'});return 'New Client is ready. Add the business and email; the portal will send the setup invitation.';}
 if(/rep|sales/.test(s)){document.querySelector('#staff-management')?.scrollIntoView({behavior:'smooth'});return 'I opened Sales Rep Access so you can add, invite, assign, or remove a rep.';}
 if(/contract|agreement/.test(s)){return selected?'Your selected client is ready. Open Contracts below to create or review the agreement.':'Choose a client first, then open Contracts. I kept this gated so a contract cannot land on the wrong account.';}
 if(/invoice|payment/.test(s))return selected?'Open Invoices below for the selected client.':'Choose a client and I’ll take you to their invoices.';
 if(/follow|attention|today|need/.test(s))return 'Your Next Actions panel shows the accounts to review first. Open any client directly from there.';
 return 'I can route you to clients, reps, contracts, invoices, reports and account actions. Full AI actions can plug into this same command bar next.';
}
document.addEventListener('DOMContentLoaded',()=>{
 $('#quick-new-client')?.addEventListener('click',()=>{$('#choose-new-client').click();document.querySelector('.admin-console')?.scrollIntoView({behavior:'smooth'});});
 $('#quick-existing-client')?.addEventListener('click',()=>{$('#choose-existing-client').click();document.querySelector('.admin-console')?.scrollIntoView({behavior:'smooth'});});
 $('#goat-admin-send')?.addEventListener('click',()=>{const q=$('#goat-admin-input').value.trim();if(!q)return;$('#goat-admin-response').textContent=goatAdminReply(q);});
 $('#goat-admin-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#goat-admin-send').click();});
});

function setupSalesHome(clients){
 const sc=$('#sales-client');if(!sc)return;
 sc.replaceChildren(new Option('Select a client',''));
 clients.forEach(c=>sc.add(new Option(c.name+' - '+c.email,c.id)));
 sc.value=selected;
 $('#sales-metric-clients').textContent=clients.length;
 $('#sales-metric-actions').textContent=clients.length;
 const box=$('#sales-next-actions');box.replaceChildren();
 if(!clients.length){box.append(node('p','No clients assigned yet. Create a new client or ask an admin for an assignment.','muted'));return;}
 clients.forEach(c=>{const row=node('div','','next-action'),copy=node('div');copy.append(node('strong',c.name),node('p','Open account and move the relationship forward.','muted'));const b=node('button','Open','secondary');b.type='button';b.onclick=()=>openSalesClient(c.id);row.append(copy,b);box.append(row);});
}
function openSalesClient(id){
 selected=id;const main=$('#client'),sales=$('#sales-client');if(main)main.value=id;if(sales)sales.value=id;
 setClientMode('existing');$('#workspace').hidden=false;
 refresh().then(()=>{const contracts=window.__portalItems?.filter?.(i=>i.kind==='contract').length;const m=$('#sales-metric-contracts');if(m)m.textContent=contracts??'-';}).catch(e=>notice(e.message));
 $('#workspace').scrollIntoView({behavior:'smooth'});
}
function salesGoat(q){
 const s=q.toLowerCase();
 if(/new|create|add/.test(s)&&/client|customer|lead/.test(s)){ $('#choose-new-client').click();document.querySelector('.admin-console')?.scrollIntoView({behavior:'smooth'});return 'New client form is ready. Add the business and email and the account will be assigned to you.';}
 if(/contract|agreement/.test(s)){if(!selected)return 'Choose a client first, then I can take you to Contracts.';document.querySelector('[data-tab="contracts"]')?.click();$('#workspace').scrollIntoView({behavior:'smooth'});return 'Contracts opened for your selected client.';}
 if(/who|next|follow|today|work/.test(s))return 'Start with the first account under Who to work next. Open it and the client workspace gives you the available next actions.';
 return 'I can help you open a client, create a client, get to contracts, or decide what to work next.';
}
document.addEventListener('DOMContentLoaded',()=>{
 $('#sales-client')?.addEventListener('change',e=>{if(e.target.value)openSalesClient(e.target.value);});
 $('#sales-open-client')?.addEventListener('click',()=>{const v=$('#sales-client')?.value;if(v)openSalesClient(v);else $('#sales-client')?.focus();});
 $('#sales-new-client')?.addEventListener('click',()=>{$('#choose-new-client').click();document.querySelector('.admin-console')?.scrollIntoView({behavior:'smooth'});});
 $('#goat-sales-send')?.addEventListener('click',()=>{const q=$('#goat-sales-input').value.trim();if(q)$('#goat-sales-response').textContent=salesGoat(q);});
 $('#goat-sales-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#goat-sales-send').click();});
});

let adminAssignedClients=new Set();
async function loadAdminAssignments(){try{const d=await api('/admin-assignments');adminAssignedClients=new Set(d.clients);const cb=$('#assign-dmitriy');if(cb)cb.checked=!!selected&&adminAssignedClients.has(selected);}catch(e){notice(e.message);}}
$('#assign-dmitriy')?.addEventListener('change',async e=>{if(!selected){e.target.checked=false;notice('Select a client first.');return;}e.target.disabled=true;try{await api('/admin-assignment',{method:'POST',body:JSON.stringify({client:selected,assigned:e.target.checked})});await loadAdminAssignments();notice(e.target.checked?'Client assigned to Dmitriy Movsesyan.':'Client removed from Dmitriy Movsesyan.');}catch(err){e.target.checked=!e.target.checked;notice(err.message);}finally{e.target.disabled=false;}});
$('#client')?.addEventListener('change',()=>{const cb=$('#assign-dmitriy');if(cb)cb.checked=!!selected&&adminAssignedClients.has(selected);});
form('report-draft-form',async(d,f)=>{if(!selected)throw Error('Select a client before creating a report.');const files=[...($('#report-source-files')?.files||[])],documents=[];for(const file of files){const fd=new FormData();fd.append('file',file);const uploaded=await api(path('/report-source-upload'),{method:'POST',body:fd});documents.push(uploaded);}const payload={title:d.get('title'),data:d.get('data'),instructions:d.get('instructions'),periodStart:d.get('periodStart'),periodEnd:d.get('periodEnd'),comparison:d.get('comparison'),compareStart:d.get('compareStart'),compareEnd:d.get('compareEnd'),sources:d.getAll('sources'),documents,includeComparison:d.get('includeComparison')==='on'};const draft=await api(path('/report-draft'),{method:'POST',body:JSON.stringify(payload)});notice('GOAT is analyzing the report sources…');const generated=await api(path('/report-generate'),{method:'POST',body:JSON.stringify({draftId:draft.id})});const report=generated.report||{};currentReportId=generated.id;$('#report-preview-title').textContent=payload.title;$('#goat-win').textContent=report.biggestWin||'No supported win identified.';$('#goat-opportunity').textContent=report.biggestOpportunity||'No supported opportunity identified.';$('#goat-change').textContent=report.whatChanged||'No supported change identified.';$('#goat-attention').textContent=report.needsAttention||'No supported issue identified.';const body=$('#report-preview-body');body.replaceChildren();if(report.executiveSummary)body.append(node('p',report.executiveSummary));(Array.isArray(report.gamePlan)?report.gamePlan:[]).forEach((x,i)=>body.append(node('p',(i+1)+'. '+x)));const deck=$('#report-preview');deck.querySelectorAll('.generated-report-slide').forEach(x=>x.remove());(Array.isArray(report.slides)?report.slides:[]).forEach(s=>{const slide=node('article','','report-slide generated-report-slide');slide.append(node('span','DETCORD / REPORT','eyebrow'),node('h2',s.title||'Report'));if(s.subtitle)slide.append(node('p',s.subtitle,'muted'));const ul=node('ul');(Array.isArray(s.bullets)?s.bullets:[]).forEach(b=>ul.append(node('li',b)));slide.append(ul);const brand=document.createElement('img');brand.className='report-slide-brand';brand.src='/detcord-logo-transparent.png';brand.alt='Detcord Digital';slide.append(brand);deck.insertBefore(slide,deck.querySelector('.report-slide-brand')||deck.querySelector('.report-export-bar'));});$('#report-preview').hidden=false;f.closest('.report-studio').hidden=true;await refresh();notice('GOAT Insights report generated.');});
$('#report-source-files')?.addEventListener('change',e=>{const box=$('#report-source-file-list'),files=[...e.target.files];box.textContent=files.length?files.map(f=>f.name).join(' · '):'';});
$('#report-print')?.addEventListener('click',()=>{document.body.classList.add('printing-report');window.print();setTimeout(()=>document.body.classList.remove('printing-report'),500);});
let reportSlideIndex=0;
function reportSlides(){return [...document.querySelectorAll('#report-preview .report-slide')];}
function showReportSlide(i){const slides=reportSlides();if(!slides.length)return;reportSlideIndex=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active-report-slide',n===reportSlideIndex));const count=$('#report-slide-count');if(count)count.textContent=(reportSlideIndex+1)+' / '+slides.length;}
function startReportPresentation(){const deck=$('#report-preview');deck.classList.add('presentation-mode');['#report-prev','#report-next','#report-exit-present','#report-slide-count'].forEach(x=>{$(x).hidden=false;});['#report-present','#report-print','#report-publish','#report-close-preview'].forEach(x=>{$(x).hidden=true;});showReportSlide(0);deck.requestFullscreen?.().catch(()=>{});}
function stopReportPresentation(){const deck=$('#report-preview');deck.classList.remove('presentation-mode');reportSlides().forEach(s=>s.classList.remove('active-report-slide'));['#report-prev','#report-next','#report-exit-present','#report-slide-count'].forEach(x=>{$(x).hidden=true;});['#report-present','#report-print','#report-publish','#report-close-preview'].forEach(x=>{$(x).hidden=false;});if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});}
$('#report-present')?.addEventListener('click',startReportPresentation);
$('#report-prev')?.addEventListener('click',()=>showReportSlide(reportSlideIndex-1));
$('#report-next')?.addEventListener('click',()=>showReportSlide(reportSlideIndex+1));
$('#report-exit-present')?.addEventListener('click',stopReportPresentation);
document.addEventListener('keydown',e=>{if(!$('#report-preview')?.classList.contains('presentation-mode'))return;if(e.key==='ArrowRight'||e.key===' '){e.preventDefault();showReportSlide(reportSlideIndex+1);}if(e.key==='ArrowLeft'){e.preventDefault();showReportSlide(reportSlideIndex-1);}if(e.key==='Escape')stopReportPresentation();});
$('#report-publish')?.addEventListener('click',async()=>{if(!currentReportId)return notice('Open or generate a saved report first.');if(!confirm('Are you sure you want to load this report to the customer portal? The customer will be able to see it.'))return;try{await api(path('/report-publish'),{method:'POST',body:JSON.stringify({id:currentReportId})});notice('Report loaded to the customer portal.');await refresh();}catch(e){notice(e.message);}});
$('#report-close-preview')?.addEventListener('click',()=>{$('#report-preview').hidden=true;$('#report-draft-form').hidden=false;});

document.querySelector('#report-draft-form select[name="comparison"]')?.addEventListener('change',e=>{$('#custom-report-dates').hidden=e.target.value!=='custom';});
(function setReportDates(){const f=$('#report-draft-form');if(!f)return;const end=new Date(),start=new Date(end);start.setDate(end.getDate()-29);const iso=d=>d.toISOString().slice(0,10);f.elements.periodEnd.value=iso(end);f.elements.periodStart.value=iso(start);})();
