// Detcord service catalog. `origin: 'spec'` = approved list from the portal spec;
// `origin: 'proposed'` = additions suggested 2026-10-08, pending Dima's review.
// Prices are intentionally blank; admins set them in Settings.
// Rejected offerings (never add): video production, recruitment marketing,
// influencer/creator marketing, link acquisition, animation, marketing due-diligence audits.

export const SERVICE_CATEGORIES = [
  { id: 'get-found', name: 'Get found' },
  { id: 'get-leads', name: 'Get leads' },
  { id: 'convert', name: 'Convert and keep customers' },
  { id: 'build', name: 'Build' },
  { id: 'brand', name: 'Brand and reputation' },
  { id: 'run', name: 'Strategy, data and operations' },
];

export const SERVICES = [
  { id: 'seo', name: 'SEO (on-page, technical and local)', category: 'get-found', origin: 'spec',
    description: 'Rank in Google search and the map pack for the services and towns that bring revenue.' },
  { id: 'gbp', name: 'Google Business Profile management', category: 'get-found', origin: 'proposed',
    description: 'Posts, photos, Q&A, categories, hours and service areas kept current every week.' },
  { id: 'citations', name: 'Directory listings and citations', category: 'get-found', origin: 'proposed',
    description: 'Consistent name, address and phone across Yelp, Apple Maps, Bing, BBB, Angi and industry directories.' },
  { id: 'ai-search', name: 'AI search visibility', category: 'get-found', origin: 'proposed',
    description: 'Show up when customers ask ChatGPT, Google AI Overviews, Gemini or Perplexity for a recommendation.' },
  { id: 'ppc', name: 'PPC advertising (Google, Meta, TikTok, LinkedIn, YouTube, retargeting)', category: 'get-leads', origin: 'spec',
    description: 'Paid campaigns built around cost per lead and booked jobs, not clicks.' },
  { id: 'lsa', name: 'Google Local Services Ads', category: 'get-leads', origin: 'proposed',
    description: 'Google Guaranteed / Screened listings at the top of search, pay per lead, with dispute management.' },
  { id: 'social', name: 'Social media management', category: 'get-leads', origin: 'spec',
    description: 'Consistent posting, community replies and content calendars across Facebook, Instagram and more.' },
  { id: 'content', name: 'Content marketing', category: 'get-leads', origin: 'spec',
    description: 'Service pages, blogs, guides and FAQs that answer what buyers search for.' },
  { id: 'email-sms', name: 'Email and SMS marketing', category: 'convert', origin: 'spec',
    description: 'Newsletters, promotions, reminders and win-back campaigns to the customers you already have.' },
  { id: 'lead-response', name: 'Lead response: call tracking, missed-call text-back and AI receptionist', category: 'convert', origin: 'proposed',
    description: 'Never lose a lead to voicemail. Track every call source, text back missed calls instantly, answer after hours.' },
  { id: 'booking', name: 'Online booking and scheduling', category: 'convert', origin: 'proposed',
    description: 'Let customers book, request quotes or pick appointment times from the website, Google and social.' },
  { id: 'referral', name: 'Referral and reactivation campaigns', category: 'convert', origin: 'proposed',
    description: 'Turn past customers into repeat jobs and referrals with automated outreach.' },
  { id: 'web', name: 'Web design, development and conversion optimization', category: 'build', origin: 'spec',
    description: 'Fast, mobile-first websites and landing pages built to turn visitors into calls and bookings.' },
  { id: 'hosting', name: 'Website hosting, maintenance and security', category: 'build', origin: 'proposed',
    description: 'Managed hosting, updates, backups, uptime monitoring and small edits handled for you.' },
  { id: 'accessibility', name: 'Website accessibility (ADA/WCAG) remediation', category: 'build', origin: 'proposed',
    description: 'Fix accessibility issues that block customers and create legal exposure.' },
  { id: 'mobile-app', name: 'Mobile app design and development', category: 'build', origin: 'spec',
    description: 'Customer or staff apps for booking, loyalty, ordering or field work.' },
  { id: 'custom-crm', name: 'Custom CRM development', category: 'build', origin: 'spec',
    description: 'A CRM shaped around how your business actually sells and delivers.' },
  { id: 'ecommerce', name: 'E-commerce marketing', category: 'build', origin: 'proposed',
    description: 'Online store setup, product feeds, shopping ads and cart recovery.' },
  { id: 'branding', name: 'Branding, identity, logos and copy', category: 'brand', origin: 'spec',
    description: 'Logo, visual identity, messaging and the words on every page and ad.' },
  { id: 'reputation', name: 'Reputation management', category: 'brand', origin: 'spec',
    description: 'More five-star reviews, faster replies, and a plan for the bad ones.' },
  { id: 'pr', name: 'Public relations', category: 'brand', origin: 'spec',
    description: 'Local press, community features, awards and announcements.' },
  { id: 'analytics', name: 'Analytics and reporting', category: 'run', origin: 'spec',
    description: 'Know which marketing produces revenue: tracking, attribution and plain-English monthly reports.' },
  { id: 'automation', name: 'Marketing automation and CRM', category: 'run', origin: 'spec',
    description: 'Follow-ups, pipelines, reminders and handoffs that run without someone remembering to do them.' },
  { id: 'strategy', name: 'Strategy, go-to-market and fractional CMO', category: 'run', origin: 'spec',
    description: 'A senior marketing lead who sets the plan, budget and priorities with you.' },
  { id: 'multi-location', name: 'Multi-location marketing', category: 'run', origin: 'proposed',
    description: 'Location pages, profiles, ads and reporting for businesses with more than one location.' },
  { id: 'competitive', name: 'Competitive intelligence', category: 'run', origin: 'proposed',
    description: 'Track what competitors rank for, spend on and promote, and where they are weak.' },
  { id: 'ai-enablement', name: 'AI implementation and staff training', category: 'run', origin: 'proposed',
    description: 'Put AI tools to work in the office (quotes, replies, scheduling) and train the team to use them.' },
];

export const serviceById = Object.fromEntries(SERVICES.map((s) => [s.id, s]));
